export const STRINGS = {
  network_error_msg: '',
  project_name: 'SR KDS',
  member_login: 'MEMBER LOGIN',
  id: '아이디',
  password: '비밀번호',
  login: '로그인',
  notification: '알림',
  confirm: '확인',
  selected_order_no: '선택\n주문번호',
  total_order_cnt: '총 주문\n건수',
  mode_section: 1,
  mode_expo: 0,
  complete_all: '전체완료',
  restore_recent: '직전복원',
  restore_search: '조회복원',
  exit_app: '프로그램 종료',
  exit_app_msg: '프로그램을\n종료하시겠습니까?',
  save_setting_msg: "설정 정보를\n저장하시겠습니까?",
  download_msg: "최신 버전을 다운로드하고\n설치하시겠습니까?",
  install_msg: "앱을 종료하고\n업데이트를 설치하시겠습니까?",
  alert: '알림',
  status_pending:"2",
  status_call:"3",
  status_completed:"5",
  restore:"복원",
  no_order_msg:"완료할 주문이 없습니다.",
};
